trigger:
- main

pr: none

resources:
  repositories: 
    - repository: Catalog
      type: git
      name: MyFirstProject/Template2


pool: my-pc

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
