trigger:
- main

pr: none

resources:
  repositories:
    - repository: almtemplates
      type: git
      name: MyFirstProject/devops_pipelines
 
    - repository: Catalog
      type: git
      name: MyFirstProject/Template


pool: my-pc

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
